export { discoverSocket } from './discover.js'
export { HrcClient } from './client.js'
export type {
  AdoptRuntimeRequest,
  AttachDescriptor,
  BridgeListFilter,
  BindSurfaceRequest,
  CaptureResponse,
  ClearContextRequest,
  ClearContextResponse,
  CloseBridgeRequest,
  DeliverBridgeRequest,
  DeliverBridgeResponse,
  DispatchTurnRequest,
  DispatchTurnResponse,
  EnsureRuntimeRequest,
  EnsureRuntimeResponse,
  HealthResponse,
  LaunchListFilter,
  RegisterBridgeTargetRequest,
  RegisterBridgeTargetResponse,
  RestartStyle,
  ResolveSessionRequest,
  ResolveSessionResponse,
  RuntimeActionResponse,
  RuntimeListFilter,
  SendInFlightInputRequest,
  SendInFlightInputResponse,
  SessionFilter,
  StatusResponse,
  SurfaceListFilter,
  UnbindSurfaceRequest,
  WatchOptions,
} from './types.js'
export type {
  HrcLaunchRecord as LaunchRecord,
  HrcLocalBridgeRecord as LocalBridgeRecord,
  HrcRuntimeSnapshot as RuntimeRecord,
  HrcSurfaceBindingRecord as SurfaceBindingRecord,
} from 'hrc-core'
