export { discoverSocket } from './discover.js'
export { HrcClient } from './client.js'
export type {
  AdoptRuntimeRequest,
  AttachDescriptor,
  AttachRuntimeRequest,
  AttachRuntimeResponse,
  BridgeListFilter,
  BindSurfaceRequest,
  CaptureResponse,
  ClearContextRequest,
  ClearContextResponse,
  CloseBridgeRequest,
  DeliverBridgeRequest,
  DeliverBridgeResponse,
  DispatchTurnRequest,
  DispatchTurnResponse,
  EnsureRuntimeRequest,
  EnsureRuntimeResponse,
  HealthResponse,
  LaunchListFilter,
  RegisterBridgeTargetRequest,
  RegisterBridgeTargetResponse,
  RestartStyle,
  ResolveSessionRequest,
  ResolveSessionResponse,
  StartRuntimeRequest,
  StartRuntimeResponse,
  RuntimeActionResponse,
  RuntimeListFilter,
  SendInFlightInputRequest,
  SendInFlightInputResponse,
  SessionFilter,
  StatusResponse,
  SurfaceListFilter,
  UnbindSurfaceRequest,
  WatchOptions,
  TargetListFilter,
  WatchMessagesOptions,
  EnsureTargetRequest,
  EnsureTargetResponse,
  DispatchTurnBySelectorRequest,
  DispatchTurnBySelectorResponse,
  DeliverLiteralBySelectorRequest,
  DeliverLiteralBySelectorResponse,
  CaptureBySelectorRequest,
  CaptureBySelectorResponse,
  CreateMessageRequest,
  CreateMessageResponse,
  ListMessagesRequest,
  ListMessagesResponse,
  WatchMessagesRequest,
  WaitMessageRequest,
  WaitMessageResponse,
  SemanticDmRequest,
  SemanticDmResponse,
} from './types.js'
export type {
  HrcLaunchRecord as LaunchRecord,
  HrcLocalBridgeRecord as LocalBridgeRecord,
  HrcRuntimeSnapshot as RuntimeRecord,
  HrcSurfaceBindingRecord as SurfaceBindingRecord,
} from 'hrc-core'
