export { discoverSocket } from './discover.js'
export { HrcClient } from './client.js'
export {
  formatAgentNotFound,
  renderCommandRoster,
  writePlacementWarnings,
} from './cli-helpers.js'
export {
  applyDotEnvFile,
  isCredentialClassKey,
  loadDotEnvLocal,
  parseDotEnvContent,
  warnAutoLoadedCredentials,
} from './dotenv-local.js'
// Re-exported from hrc-core, where the assembly now lives so the daemon can
// reach it too (T-07615). Every existing `from 'hrc-sdk'` import is unchanged.
export {
  applyProvisionDirectives,
  buildHrcRuntimeIntent,
  harnessFrontendToHrcHarness,
  resolveAgentHarness,
} from 'hrc-core'
export type {
  BuildHrcRuntimeIntentInput,
  ResolvedAgentHarness,
} from 'hrc-core'
export { resolveProfileAwareScopeInput } from './resolve-scope.js'
export type {
  ProfileAwareScopeDefaults,
  ProfileAwareResolvedScopeInput,
  ResolveProfileAwareScopeInputOptions,
} from './resolve-scope.js'
export type {
  AdoptRuntimeRequest,
  AttachDescriptor,
  AttachRuntimeRequest,
  AttachRuntimeResponse,
  BridgeListFilter,
  BrokerForensicsOptions,
  BrokerForensicsResponse,
  BindSurfaceRequest,
  CaptureResponse,
  ClearContextRequest,
  ClearContextResponse,
  CloseBridgeRequest,
  DeliverBridgeRequest,
  DeliverBridgeResponse,
  DispatchTurnRequest,
  DispatchTurnResponse,
  EnsureRuntimeRequest,
  EnsureRuntimeResponse,
  HealthResponse,
  HrcSubscriberAdmissionSnapshot,
  LatestEventBySessionFilter,
  LaunchListFilter,
  RegisterBridgeTargetRequest,
  RegisterBridgeTargetResponse,
  RestartStyle,
  ResolveSessionRequest,
  ResolveSessionResponse,
  StartRuntimeRequest,
  StartRuntimeResponse,
  RuntimeActionResponse,
  KillBrokerTmuxLeasesResponse,
  RuntimeListFilter,
  RuntimeListPage,
  RunListFilter,
  SendInFlightInputRequest,
  SendInFlightInputResponse,
  SessionFilter,
  SessionEffectiveStatus,
  SessionExecutionMode,
  SessionFacetsRequest,
  SessionFacetsResponse,
  SessionPageFilters,
  SessionPageItem,
  SessionPageRequest,
  SessionPageResponse,
  SessionProjectionResult,
  SessionPeerStatus,
  SessionTitleRecord,
  SessionTitleSource,
  SetSessionTitleRequest,
  DeleteSessionTitleResponse,
  StatusResponse,
  StatusSummaryResponse,
  SurfaceListFilter,
  UnbindSurfaceRequest,
  InvocationEventEnvelope,
  WatchBrokerEventsOptions,
  WatchBoundedEventsOptions,
  HrcEventTailOptions,
  WatchOptions,
  TargetListFilter,
  WatchMessagesOptions,
  EnsureTargetRequest,
  EnsureTargetResponse,
  DispatchTurnBySelectorRequest,
  DispatchTurnBySelectorResponse,
  DeliverLiteralBySelectorRequest,
  DeliverLiteralBySelectorResponse,
  CaptureBySelectorRequest,
  CaptureBySelectorResponse,
  CreateMessageRequest,
  CreateMessageResponse,
  ListMessagesRequest,
  ListMessagesResponse,
  OpenBrokerSessionRequest,
  OpenBrokerSessionResponse,
  WatchMessagesRequest,
  WaitMessageRequest,
  WaitMessageResponse,
  SemanticDmRequest,
  SemanticDmResponse,
  TranscriptIndexRebuildResponse,
  TranscriptIndexStats,
  TranscriptSearchHit,
  TranscriptSearchRequest,
  TranscriptSearchResponse,
  TranscriptTerminalStatus,
} from './types.js'
export type {
  HrcBoundedEventStreamRecord,
  HrcEventTail,
  HrcMailAckRequest,
  HrcMailAckResponse,
  HrcMailActor,
  HrcMailCatRequest,
  HrcMailCatResponse,
  HrcMailDeferRequest,
  HrcMailDeferResponse,
  HrcMailDispositionResult,
  HrcMailEnvelope,
  HrcMailEnvelopeState,
  HrcMailInboxRequest,
  HrcMailInboxResponse,
  HrcMailListRequest,
  HrcMailListResponse,
  HrcMailPayload,
  HrcMailReceipt,
  HrcMailReplySchema,
  HrcMailSendRequest,
  HrcMailSendResponse,
  HrcLaunchRecord as LaunchRecord,
  HrcLocalBridgeRecord as LocalBridgeRecord,
  HrcRunRecord as RunRecord,
  HrcRuntimeSnapshot as RuntimeRecord,
  HrcSurfaceBindingRecord as SurfaceBindingRecord,
} from 'hrc-core'
