import {
  askBracketScanIndexMigration,
  brokerCommittedProjectionCursorMigration,
  brokerTurnAttributionMigration,
  eventRepositoryQueryIndexesMigration,
  observationalEventProvenanceMigration,
  pruneCandidateIndexesMigration,
  runBrokerSubmissionIdMigration,
  runsDispatchIdempotencyMigration,
  runtimePresentationRecordMigration,
  steerContributionsMigration,
  submissionLookupIndexesMigration,
  transcriptTurnIndexMigration,
} from './broker-migrations-events.js'
import {
  format2InputEventIndexJsonGuardMigration,
  format2InputsAndObservedRunsMigration,
  participantRuntimeOwnershipRepairMigration,
  retainedEvidenceMigration,
  runtimeOperationAspPreparationMigration,
  submissionAdmissionsMigration,
} from './broker-migrations-format2.js'
import {
  brokerEventIdentityMigration,
  brokerFullEnvelopeMigration,
  brokerPersistenceMigration,
  lifecyclePolicyAuditMigration,
  permissionIdentityMigration,
  runsBrokerInputFenceMigration,
  runsDispatchedInputIdMigration,
  runtimeArtifactOperationKindMigration,
  runtimeBrokerStateMigration,
  runtimeLifecycleStateMigration,
} from './broker-migrations-persistence.js'
import type { HrcMigration } from './types.js'

export const brokerMigrations: readonly HrcMigration[] = [
  brokerPersistenceMigration,
  runtimeBrokerStateMigration,
  runsDispatchedInputIdMigration,
  lifecyclePolicyAuditMigration,
  runtimeLifecycleStateMigration,
  permissionIdentityMigration,
  brokerEventIdentityMigration,
  brokerFullEnvelopeMigration,
  runtimeArtifactOperationKindMigration,
  runsBrokerInputFenceMigration,
  observationalEventProvenanceMigration,
  runsDispatchIdempotencyMigration,
  eventRepositoryQueryIndexesMigration,
  steerContributionsMigration,
  runtimePresentationRecordMigration,
  pruneCandidateIndexesMigration,
  brokerCommittedProjectionCursorMigration,
  runBrokerSubmissionIdMigration,
  transcriptTurnIndexMigration,
  brokerTurnAttributionMigration,
  askBracketScanIndexMigration,
  participantRuntimeOwnershipRepairMigration,
  runtimeOperationAspPreparationMigration,
  retainedEvidenceMigration,
  submissionAdmissionsMigration,
  submissionLookupIndexesMigration,
  format2InputsAndObservedRunsMigration,
  format2InputEventIndexJsonGuardMigration,
]
