// ── Canonical SQL column lists ──────────────────────────────────────────
// Each constant enumerates the columns for a given row shape exactly once.
// Every SELECT in the repository layer references these constants so that
// column additions/removals are a single-site change.

export const SESSION_COLUMNS = `
  host_session_id,
  scope_ref,
  lane_ref,
  generation,
  status,
  prior_host_session_id,
  created_at,
  updated_at,
  last_applied_intent_json,
  continuation_json`

export const RUNTIME_COLUMNS = `
  runtime_id,
  host_session_id,
  scope_ref,
  lane_ref,
  generation,
  transport,
  harness,
  provider,
  status,
  status_changed_at,
  tmux_json,
  supports_inflight_input,
  active_run_id,
  last_activity_at,
  controller_kind,
  active_operation_id,
  active_invocation_id,
  plan_hash,
  selected_profile_hash,
  runtime_state_json,
  lifecycle_terminal_reason,
  presentation_json,
  created_at,
  updated_at`

export const RUN_COLUMNS = `
  run_id,
  host_session_id,
  runtime_id,
  scope_ref,
  lane_ref,
  generation,
  transport,
  status,
  accepted_at,
  started_at,
  completed_at,
  updated_at,
  error_code,
  error_message,
  execution_format,
  turn_key,
  native_turn_id,
  native_harness_generation,
  native_turn_attempt,
  initiating_input_id,
  ownership_conflict_json,
  observation_state,
  observed_start_hrc_seq,
  operation_id,
  invocation_id,
  dispatched_input_id,
  broker_submission_id,
  broker_input_fenced_at,
  broker_input_fence_reason,
  dispatch_idempotency_key,
  queue_snapshot_id,
  queued_input_seq,
  queue_snapshot_position,
  coalesced_into_run_id,
  coalesced_position,
  origin_actor,
  origin_kind,
  origin_causation_ref`

export const EVENT_COLUMNS = `
  seq,
  stream_seq,
  ts,
  host_session_id,
  scope_ref,
  lane_ref,
  generation,
  run_id,
  runtime_id,
  source,
  event_kind,
  event_json`

export const HRC_EVENT_COLUMNS = `
  hrc_seq,
  stream_seq,
  source_ref,
  origin_seq,
  ts,
  host_session_id,
  scope_ref,
  lane_ref,
  generation,
  runtime_id,
  run_id,
  launch_id,
  app_id,
  app_session_key,
  category,
  event_kind,
  transport,
  error_code,
  replayed,
  evidence_origin,
  payload_json`

export const LOCAL_BRIDGE_COLUMNS = `
  bridge_id,
  host_session_id,
  runtime_id,
  transport,
  target,
  expected_host_session_id,
  expected_generation,
  status,
  created_at,
  closed_at`

export const SURFACE_BINDING_COLUMNS = `
  surface_kind,
  surface_id,
  client_tty,
  host_session_id,
  runtime_id,
  generation,
  window_id,
  pane_id,
  bound_at,
  unbound_at,
  reason`

export const RUNTIME_BUFFER_COLUMNS = `
  runtime_id,
  run_id,
  chunk_seq,
  text,
  created_at`

export const ACTIVE_INPUT_DELIVERY_COLUMNS = `
  input_application_id,
  input_attempt_id,
  idempotency_key,
  host_session_id,
  generation,
  runtime_id,
  run_id,
  status,
  request_json,
  response_json,
  error_code,
  error_message,
  created_at,
  updated_at`
