import { mkdir, readFile, readdir, stat, writeFile } from 'node:fs/promises'
import { dirname, join, relative, resolve } from 'node:path'

type RecordValue = string | string[] | Record<string, string> | null
type ArchitectureRecord = Record<string, RecordValue> & { file: string }

const root = resolve(new URL('..', import.meta.url).pathname)
const writeMode = process.argv.includes('--write')
const project = JSON.parse(await readFile(join(root, 'package.json'), 'utf8')).name as string
const generated = '<!-- GENERATED by `just architecture-records --write`. DO NOT EDIT BY HAND. -->'

function scalar(raw: string): RecordValue {
  const value = raw.trim()
  if (value === 'null') return null
  if (value === '[]') return []
  if (
    (value.startsWith('"') && value.endsWith('"')) ||
    (value.startsWith("'") && value.endsWith("'"))
  ) {
    return value.slice(1, -1)
  }
  return value
}

function parseRecord(text: string, file: string): ArchitectureRecord {
  const record: ArchitectureRecord = { file }
  const lines = text.replace(/\r\n/g, '\n').split('\n')
  for (let index = 0; index < lines.length; index += 1) {
    const line = lines[index] ?? ''
    if (line.trim() === '' || line.trimStart().startsWith('#')) continue
    const match = /^([a-z_]+):(?:\s*(.*))?$/.exec(line)
    if (match?.[1] === undefined) throw new Error(`${file}:${index + 1}: invalid top-level YAML`)
    const key = match[1]
    const raw = match[2] ?? ''
    if (raw === '|' || raw === '>') {
      const parts: string[] = []
      while ((lines[index + 1] ?? '').startsWith('  ')) {
        index += 1
        parts.push((lines[index] ?? '').slice(2))
      }
      record[key] = raw === '>' ? parts.join(' ').replace(/\s+/g, ' ').trim() : parts.join('\n')
      continue
    }
    if (raw === '') {
      const children: string[] = []
      while ((lines[index + 1] ?? '').startsWith('  ')) {
        index += 1
        const child = (lines[index] ?? '').slice(2)
        if (child.trim() !== '') children.push(child)
      }
      if (children.every((child) => child.startsWith('- '))) {
        record[key] = children.map((child) => String(scalar(child.slice(2))))
      } else {
        record[key] = Object.fromEntries(
          children.map((child) => {
            const nested = /^([a-z_]+):\s*(.*)$/.exec(child)
            if (nested?.[1] === undefined) throw new Error(`${file}: invalid nested YAML`)
            return [nested[1], String(scalar(nested[2] ?? ''))]
          })
        )
      }
      continue
    }
    record[key] = scalar(raw)
  }
  return record
}

async function filesUnder(kind: 'invariants' | 'risks'): Promise<string[]> {
  const directory = join(root, 'architecture', 'records', kind)
  try {
    return (await readdir(directory))
      .filter((name) => name.endsWith('.yaml'))
      .map((name) => join(directory, name))
      .sort()
  } catch {
    return []
  }
}

function requireFields(record: ArchitectureRecord, fields: string[], findings: string[]): void {
  for (const field of fields) {
    if (!(field in record) || record[field] === '') {
      findings.push(`${record.file}: missing ${field}`)
    }
  }
}

async function validate(records: ArchitectureRecord[]): Promise<string[]> {
  const findings: string[] = []
  const ids = new Set<string>()
  for (const record of records) {
    const id = String(record['id'] ?? '')
    const kind = String(record['kind'] ?? '')
    const expected = relative(root, join(dirname(record.file), `${id}.yaml`))
    if (!/^[a-z0-9][a-z0-9.-]*$/.test(id)) findings.push(`${record.file}: invalid id`)
    if (ids.has(id)) findings.push(`${record.file}: duplicate id ${id}`)
    ids.add(id)
    if (relative(root, record.file) !== expected) findings.push(`${record.file}: id/path mismatch`)
    if (record['status'] !== 'active') findings.push(`${record.file}: records must be active`)
    if (kind === 'invariant') {
      requireFields(
        record,
        [
          'id',
          'kind',
          'status',
          'owner_project',
          'scope',
          'predicate',
          'authority',
          'source',
          'required_tests',
          'last_verified',
          'reopen_when',
          'supersedes',
          'superseded_by',
        ],
        findings
      )
    } else if (kind === 'accepted_risk') {
      requireFields(
        record,
        [
          'id',
          'kind',
          'status',
          'owner_project',
          'accepted_by',
          'date',
          'severity',
          'blast_radius',
          'mitigation',
          'expiry',
          'review_trigger',
          'reopen_when',
          'source',
          'supersedes',
          'superseded_by',
        ],
        findings
      )
    } else {
      findings.push(`${record.file}: unsupported kind ${kind}`)
    }
    const source = record['source']
    if (!Array.isArray(source) || source.length === 0) {
      findings.push(`${record.file}: source must be a non-empty list`)
    } else {
      for (const entry of source) {
        if (/^(hrcchat#|wrkq:|commit:)/.test(entry)) continue
        try {
          await stat(join(root, entry))
        } catch {
          findings.push(`${record.file}: missing source ${entry}`)
        }
      }
    }
  }

  for (const id of [
    `${project}.architecture-law`,
    `${project}.verify-gate`,
    `${project}.canonical-package-publication`,
    `${project}.observable-release`,
  ]) {
    if (!ids.has(id)) findings.push(`architecture/records: missing required record ${id}`)
  }

  const justfile = await readFile(join(root, 'justfile'), 'utf8')
  if (!/^architecture-records(?:\s|\*|:)/m.test(justfile)) {
    findings.push('justfile: missing architecture-records recipe')
  }
  if (!/^verify:[\s\S]*?^\s+just architecture-records$/m.test(justfile)) {
    findings.push('justfile: verify must run architecture-records')
  }
  return findings
}

function line(value: RecordValue): string {
  return String(value ?? '')
    .replace(/\s+/g, ' ')
    .trim()
}

function render(records: ArchitectureRecord[], kind: 'invariant' | 'accepted_risk'): string {
  const title = kind === 'invariant' ? 'Active Invariants' : 'Accepted Risks'
  const body = records
    .filter((record) => record['kind'] === kind)
    .map((record) =>
      kind === 'invariant'
        ? `## ${record['id']}\n\n${line(record['predicate'])}\n`
        : `## ${record['id']}\n\n- Severity: ${record['severity']}\n- Accepted by: ${record['accepted_by']}\n- Blast radius: ${line(record['blast_radius'])}\n- Mitigation: ${line(record['mitigation'])}\n`
    )
    .join('\n')
  return `${generated}\n\n# ${project} — ${title}${body ? `\n\n${body.trimEnd()}` : ''}\n`
}

const paths = [...(await filesUnder('invariants')), ...(await filesUnder('risks'))]
const records = await Promise.all(
  paths.map(async (path) => parseRecord(await readFile(path, 'utf8'), path))
)
const findings = await validate(records)
const projections = new Map([
  ['architecture/INVARIANTS.md', render(records, 'invariant')],
  ['architecture/RISKS.md', render(records, 'accepted_risk')],
  [
    'architecture/index.jsonl',
    `${records
      .sort((left, right) => String(left['id']).localeCompare(String(right['id'])))
      .map((record) =>
        JSON.stringify({
          id: record['id'],
          kind: record['kind'],
          status: record['status'],
          owner_project: record['owner_project'],
          source: record['source'],
        })
      )
      .join('\n')}\n`,
  ],
])

if (findings.length === 0 && writeMode) {
  for (const [path, content] of projections) {
    await mkdir(dirname(join(root, path)), { recursive: true })
    await writeFile(join(root, path), content)
  }
} else if (findings.length === 0) {
  for (const [path, expected] of projections) {
    let actual = ''
    try {
      actual = await readFile(join(root, path), 'utf8')
    } catch {}
    if (actual !== expected) findings.push(`${path}: stale; run just architecture-records --write`)
  }
}

if (findings.length > 0) {
  for (const finding of findings) console.error(`architecture-records: ${finding}`)
  process.exit(1)
}
console.log(
  `architecture-records: ${records.length} active record(s); structure and projections pass`
)
