#!/usr/bin/env bash
#
# dev-env.sh — provision and tear down the ephemeral environment the e2e suite
# needs, from a fresh clone, using nothing but image substrate.
#
# WHY THIS EXISTS. hrc-runtime is a daemon project, and its suites are honest
# about it: hrc-cli talks to a real HRC daemon over a real unix socket, and the
# hrcchat/dm paths resolve a real agent home before they will address anything.
# Historically both were satisfied *ambiently* — the operator's production
# daemon at ~/praesidium/var/run/hrc/hrc.sock and the operator's agent homes at
# ~/praesidium/var/agents. That works on exactly one machine and nowhere else,
# and it means a green suite could be reporting on the health of the running
# system rather than on the tree under test. This script replaces both ambient
# dependencies with provisioned ones (T-06896).
#
# THE INVARIANT: everything lives under one root outside the checkout, and
# nothing here ever touches the host's production daemon, state, or agents.
#
#   env-up    idempotent, self-healing, prints what it started
#   env-down  teardown; env-up after a crashed env-down still works
#
# `just verify` — the declared landing gate — depends on env-up by ruling
# (T-06900 + T-06902, joint). So this script is load-bearing for landing, not a
# convenience: if it stops provisioning honestly, the gate stops meaning
# anything. Keep it boring.
#
# The `hrc server serve` verb is deliberate. `hrc server start` probes launchd
# and kickstarts the LaunchAgent when one is loaded — on a developer laptop that
# would start (or restart) the operator's PRODUCTION daemon and ignore the
# HRC_RUNTIME_DIR pointing at our temp root. `serve` is the launchd-free
# foreground path, so we supervise it ourselves and know exactly what we killed.

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

# One root per checkout, so two worktrees do not fight over one daemon. Kept
# under TMPDIR rather than in-tree because the unix socket path underneath it is
# subject to the ~104-byte sockaddr limit, which a deep repo path can blow.
default_root() {
  local slug
  slug="$(printf '%s' "${REPO_ROOT}" | cksum | cut -d' ' -f1)"
  printf '%s/hrc-dev-env-%s-%s' "${TMPDIR:-/tmp}" "$(id -u)" "${slug}"
}

ROOT="${HRC_DEV_ENV_ROOT:-$(default_root)}"
ROOT="${ROOT%/}"
RUN_DIR="${ROOT}/run"
STATE_DIR="${ROOT}/state"
AGENTS_DIR="${ROOT}/agents"
ENV_FILE="${ROOT}/env.sh"
PID_FILE="${ROOT}/daemon.pid"
LOG_FILE="${ROOT}/daemon.log"
SOCKET="${RUN_DIR}/hrc.sock"
PROJECT_SEARCH_ROOT=""

# Every agent id the suites address. A fixture home is a directory plus an
# agent-profile.toml — the marker spaces-config actually looks for; a bare
# directory resolves as "agent not found". Ids the suites expect to be ABSENT
# (e.g. "missing") are deliberately not in this list.
FIXTURE_AGENTS=(
  cody clod rex larry smokey curly mable daedalus
  operator room-coordinator human
)

log() { printf '[dev-env] %s\n' "$*"; }
die() { printf '[dev-env] ERROR: %s\n' "$*" >&2; exit 1; }

hrc_cli() { bun "${REPO_ROOT}/packages/hrc-cli/bin/hrc.js" "$@"; }

# Liveness is the socket ANSWERING, not the socket existing: a crashed daemon
# leaves the inode behind, and treating that as "up" is how env-up stops being
# self-healing.
daemon_responds() {
  HRC_RUNTIME_DIR="${RUN_DIR}" HRC_STATE_DIR="${STATE_DIR}" \
    hrc_cli server status --json >/dev/null 2>&1
}

write_env_file() {
  cat > "${ENV_FILE}" <<EOF
# Generated by scripts/dev-env.sh — source this to point a shell at the
# ephemeral environment. Never exported globally by the recipes themselves.
export HRC_DEV_ENV_ROOT='${ROOT}'
export HRC_RUNTIME_DIR='${RUN_DIR}'
export HRC_STATE_DIR='${STATE_DIR}'
export ASP_AGENTS_ROOT='${AGENTS_DIR}'
export HRC_PROJECT_SEARCH_ROOTS='${PROJECT_SEARCH_ROOT}'
EOF
}

provision_agents() {
  local agent
  for agent in "${FIXTURE_AGENTS[@]}"; do
    mkdir -p "${AGENTS_DIR}/${agent}"
    cat > "${AGENTS_DIR}/${agent}/agent-profile.toml" <<EOF
version = 3

[identity]
display = "${agent}"

[provisioning]
harness = "codex"
EOF
    cat > "${AGENTS_DIR}/${agent}/SOUL.md" <<EOF
# ${agent}

Ephemeral hrc-runtime verification fixture.
EOF
  done
}

# env-up owns the build (T-06900/T-06902 joint ruling). Package typecheck and
# the cross-package imports both resolve siblings through their built
# dist/*.d.ts, which a fresh clone does not have.
#
# The build is UNCONDITIONAL, not "build if dist is missing". A present-but-
# stale dist — after a pull, a branch switch, a revert — is the same class of
# bug as no dist at all: the gate reads state left behind by earlier work
# instead of deriving it from the tree, and it can report green on a tree that
# is red (or the reverse). Skipping the build when dist merely *exists* would
# reintroduce the finding this recipe was written to close, in a subtler form.
# It costs ~13s.
#
# `bun install` stays conditional: this repo pulls dependencies explicitly via
# `just pull-deps` and treats bun.lock as something a gate must never advance,
# so the install here only covers the case it has to — a clone with no
# node_modules at all.
provision_build() {
  if [[ ! -d "${REPO_ROOT}/node_modules" ]]; then
    log "installing dependencies (bun install)"
    (cd "${REPO_ROOT}" && bun install)
  fi
  log "building workspace (bun run build)"
  (cd "${REPO_ROOT}" && bun run build)
}

resolve_project_search_root() {
  # A hook exports GIT_DIR/GIT_WORK_TREE for its own checkout. The helper drops
  # every GIT_* override before asking Git for the common directory, whose owner
  # is the canonical checkout even when this script runs from a linked worktree.
  # HRC marker discovery then receives the stable parent containing registered
  # project checkouts instead of borrowing HOME or the worktree's path shape.
  PROJECT_SEARCH_ROOT="$(
    bun "${REPO_ROOT}/scripts/resolve-project-search-root.ts" "${REPO_ROOT}"
  )"
  [[ -n "${PROJECT_SEARCH_ROOT}" ]] || die "canonical project search root resolved empty"
}

start_daemon() {
  if daemon_responds; then
    log "daemon already healthy on ${SOCKET} (reused)"
    return 0
  fi

  # Reaching here with files present means the previous daemon died or was
  # killed without teardown. Clear the residue rather than failing on it.
  if [[ -e "${SOCKET}" || -f "${PID_FILE}" ]]; then
    log "clearing stale daemon residue under ${RUN_DIR}"
    stop_daemon
  fi

  mkdir -p "${RUN_DIR}" "${STATE_DIR}"
  log "starting ephemeral daemon (hrc server serve) → ${LOG_FILE}"
  (
    cd "${REPO_ROOT}"
    HRC_RUNTIME_DIR="${RUN_DIR}" HRC_STATE_DIR="${STATE_DIR}" ASP_AGENTS_ROOT="${AGENTS_DIR}" \
      HRC_PROJECT_SEARCH_ROOTS="${PROJECT_SEARCH_ROOT}" \
      nohup bun "${REPO_ROOT}/packages/hrc-cli/bin/hrc.js" server serve \
      >"${LOG_FILE}" 2>&1 &
    printf '%s\n' "$!" > "${PID_FILE}"
  )

  local waited=0
  while (( waited < 60 )); do
    daemon_responds && { log "daemon healthy (pid $(cat "${PID_FILE}"))"; return 0; }
    sleep 1
    waited=$((waited + 1))
  done
  tail -20 "${LOG_FILE}" >&2 || true
  die "ephemeral daemon did not become healthy within ${waited}s"
}

# Teardown is unconditional and never fails: it has to work on a half-created
# root, on a root whose daemon is already gone, and on a root that a previous
# crashed env-down left behind.
stop_daemon() {
  if [[ -f "${PID_FILE}" ]]; then
    local pid
    pid="$(cat "${PID_FILE}" 2>/dev/null || true)"
    if [[ -n "${pid}" ]] && kill -0 "${pid}" 2>/dev/null; then
      kill "${pid}" 2>/dev/null || true
      local waited=0
      while (( waited < 10 )) && kill -0 "${pid}" 2>/dev/null; do
        sleep 1
        waited=$((waited + 1))
      done
      kill -9 "${pid}" 2>/dev/null || true
    fi
    rm -f "${PID_FILE}"
  fi
  # The daemon owns a tmux server on its own socket; killing the daemon does not
  # reap it, and a leaked tmux server keeps panes (and their processes) alive.
  if [[ -S "${RUN_DIR}/tmux.sock" ]]; then
    tmux -S "${RUN_DIR}/tmux.sock" kill-server 2>/dev/null || true
  fi
  rm -f "${SOCKET}" "${RUN_DIR}/server.lock" "${RUN_DIR}/server.pid" 2>/dev/null || true
}

cmd_up() {
  mkdir -p "${ROOT}" "${RUN_DIR}" "${STATE_DIR}" "${AGENTS_DIR}"
  provision_build
  resolve_project_search_root
  provision_agents
  start_daemon
  write_env_file

  log "environment ready"
  log "  root         ${ROOT}"
  log "  runtime dir  ${RUN_DIR}   (HRC_RUNTIME_DIR)"
  log "  state dir    ${STATE_DIR}   (HRC_STATE_DIR)"
  log "  agents root  ${AGENTS_DIR}   (ASP_AGENTS_ROOT, ${#FIXTURE_AGENTS[@]} fixture homes)"
  log "  projects     ${PROJECT_SEARCH_ROOT}   (HRC_PROJECT_SEARCH_ROOTS)"
  log "  daemon       ${SOCKET}  pid $(cat "${PID_FILE}" 2>/dev/null || echo '?')"
  log "  daemon log   ${LOG_FILE}"
  log "  env file     ${ENV_FILE}   (source it to point a shell here)"
}

cmd_down() {
  if [[ ! -d "${ROOT}" ]]; then
    log "nothing to tear down (${ROOT} absent)"
    return 0
  fi
  stop_daemon
  rm -rf "${ROOT}"
  log "environment removed (${ROOT})"
}

# Print the exports so a caller can `eval "$(scripts/dev-env.sh env)"` without
# knowing where the root landed.
cmd_env() {
  [[ -f "${ENV_FILE}" ]] || die "no environment provisioned; run 'just env-up' first"
  cat "${ENV_FILE}"
}

case "${1:-}" in
  up)   cmd_up ;;
  down) cmd_down ;;
  env)  cmd_env ;;
  *)    die "usage: dev-env.sh <up|down|env>" ;;
esac
