#!/usr/bin/env bash
#
# dev-env.sh — provision and tear down the ephemeral environment the e2e suite
# needs, from a fresh clone, using nothing but image substrate.
#
# WHY THIS EXISTS. hrc-runtime is a daemon project, and its suites are honest
# about it: hrc-cli talks to a real HRC daemon over a real unix socket, and the
# hrcchat/dm paths resolve a real agent home before they will address anything.
# Historically both were satisfied *ambiently* — the operator's production
# daemon at ~/praesidium/var/run/hrc/hrc.sock and the operator's agent homes at
# ~/praesidium/var/agents. That works on exactly one machine and nowhere else,
# and it means a green suite could be reporting on the health of the running
# system rather than on the tree under test. This script replaces both ambient
# dependencies with provisioned ones (T-06896).
#
# THE INVARIANT: everything lives under one root outside the checkout, and
# nothing here ever touches the host's production daemon, state, or agents.
#
#   env-up    idempotent, self-healing, prints what it started
#   env-down  teardown; env-up after a crashed env-down still works
#
# `just verify` — the declared landing gate — depends on env-up by ruling
# (T-06900 + T-06902, joint). So this script is load-bearing for landing, not a
# convenience: if it stops provisioning honestly, the gate stops meaning
# anything. Keep it boring.
#
# The `hrc server serve` verb is deliberate. `hrc server start` probes launchd
# and kickstarts the LaunchAgent when one is loaded — on a developer laptop that
# would start (or restart) the operator's PRODUCTION daemon and ignore the
# HRC_RUNTIME_DIR pointing at our temp root. `serve` is the launchd-free
# foreground path, so we supervise it ourselves and know exactly what we killed.

set -euo pipefail

# Physical path (-P): the slug below hashes it, and a checkout reached through a
# symlink must not get a second root.
REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd -P)"

# One root per checkout, so two worktrees do not fight over one daemon. Kept
# out of the tree because the unix socket path underneath it is subject to the
# ~104-byte sockaddr limit, which a deep repo path can blow.
#
# The base is /tmp, NOT ${TMPDIR}. TMPDIR differs between a login shell, a
# launchd job and a harness, and keying on it gave one checkout two roots, each
# with its own daemon that the other's start never saw (T-10329).
ROOT_BASE="/tmp"
ROOT_PREFIX="hrc-dev-env-$(id -u)-"
default_root() {
  local slug
  slug="$(printf '%s' "${REPO_ROOT}" | cksum | cut -d' ' -f1)"
  printf '%s/%s%s' "${ROOT_BASE}" "${ROOT_PREFIX}" "${slug}"
}

ROOT="${HRC_DEV_ENV_ROOT:-$(default_root)}"
ROOT="${ROOT%/}"
RUN_DIR="${ROOT}/run"
STATE_DIR="${ROOT}/state"
AGENTS_DIR="${ROOT}/agents"
ENV_FILE="${ROOT}/env.sh"
PID_FILE="${ROOT}/daemon.pid"
LOG_FILE="${ROOT}/daemon.log"
SOCKET="${RUN_DIR}/hrc.sock"
WRKQ_DB_FILE="${ROOT}/wrkq.db"
DAEMON_WRKQ_FILE="${ROOT}/daemon.wrkq"
OWNERS_FILE="${ROOT}/owners"
REPO_FILE="${ROOT}/repo"
WATCHDOG_PID_FILE="${ROOT}/watchdog.pid"
WATCHDOG_LOG="${ROOT}/watchdog.log"
WATCH_INTERVAL="${HRC_DEV_ENV_WATCH_INTERVAL:-2}"
PROJECT_SEARCH_ROOT=""

# Every agent id the suites address. A fixture home is a directory plus an
# agent-profile.toml — the marker spaces-config actually looks for; a bare
# directory resolves as "agent not found". Ids the suites expect to be ABSENT
# (e.g. "missing") are deliberately not in this list.
FIXTURE_AGENTS=(
  cody clod rex larry smokey curly mable daedalus
  operator room-coordinator human
)

log() { printf '[dev-env] %s\n' "$*"; }
die() { printf '[dev-env] ERROR: %s\n' "$*" >&2; exit 1; }

hrc_cli() { bun "${REPO_ROOT}/packages/hrc-cli/bin/hrc.js" "$@"; }

# Liveness is the socket ANSWERING, not the socket existing: a crashed daemon
# leaves the inode behind, and treating that as "up" is how env-up stops being
# self-healing.
daemon_responds() {
  HRC_RUNTIME_DIR="${RUN_DIR}" HRC_STATE_DIR="${STATE_DIR}" \
    hrc_cli server status --json >/dev/null 2>&1
}

write_env_file() {
  cat > "${ENV_FILE}" <<EOF
# Generated by scripts/dev-env.sh — source this to point a shell at the
# ephemeral environment. Never exported globally by the recipes themselves.
export HRC_DEV_ENV_ROOT='${ROOT}'
export HRC_RUNTIME_DIR='${RUN_DIR}'
export HRC_STATE_DIR='${STATE_DIR}'
export ASP_AGENTS_ROOT='${AGENTS_DIR}'
export HRC_PROJECT_SEARCH_ROOTS='${PROJECT_SEARCH_ROOT}'
export WRKQ_DB='${WRKQ_DB_FILE}'
unset WRKQ_DB_PATH WRKQ_DB_PATH_FILE
EOF
}

provision_agents() {
  local agent
  for agent in "${FIXTURE_AGENTS[@]}"; do
    mkdir -p "${AGENTS_DIR}/${agent}"
    cat > "${AGENTS_DIR}/${agent}/agent-profile.toml" <<EOF
version = 3

[identity]
display = "${agent}"

[provisioning]
harness = "codex"
EOF
    cat > "${AGENTS_DIR}/${agent}/SOUL.md" <<EOF
# ${agent}

Ephemeral hrc-runtime verification fixture.
EOF
  done
}

# env-up owns the build (T-06900/T-06902 joint ruling). Package typecheck and
# the cross-package imports both resolve siblings through their built
# dist/*.d.ts, which a fresh clone does not have.
#
# The build is UNCONDITIONAL, not "build if dist is missing". A present-but-
# stale dist — after a pull, a branch switch, a revert — is the same class of
# bug as no dist at all: the gate reads state left behind by earlier work
# instead of deriving it from the tree, and it can report green on a tree that
# is red (or the reverse). Skipping the build when dist merely *exists* would
# reintroduce the finding this recipe was written to close, in a subtler form.
# It costs ~13s.
#
# The install is unconditional too, and FROZEN. This repo pulls dependencies
# explicitly via `just pull-deps` and treats bun.lock as something a gate must
# never advance; `--frozen-lockfile` installs exactly what the committed lock
# names and fails rather than rewrite it. Installing only when node_modules was
# missing let a long-lived checkout keep a copy older than its own lock: the
# post-push worktree built df296269 against a 2026-10-03 spaces-aspc-protocol
# while bun.lock named 2026-10-05, and went red on APIs the lock provides
# (R-00302). An in-sync install is a no-op of about a second.
provision_build() {
  log "installing dependencies (bun install --frozen-lockfile)"
  (cd "${REPO_ROOT}" && bun install --frozen-lockfile)
  log "building workspace (bun run build)"
  (cd "${REPO_ROOT}" && bun run build)
}

# The suites shell out to `wrkq` (task state, the project registry, envelope
# reads) and, through the wrkp `just` shim, write run.settled facts. Inherited,
# WRKQ_DB points at the operator's shared ledger: the suites then read and write
# production state, and every call waits on a remote round trip — ~5s each when
# that ledger is slow, 100+ calls per run, which is what made the pre-push gate
# slow and flaky (T-09868). No assertion depends on that ledger's contents (the
# hrc-cli suite passes 839/839 with wrkq unavailable), so the environment gets
# its own empty, migrated ledger like it gets its own daemon, and so does that
# daemon (its wrkq authority reads HRC_WRKQ_DB). The path-named aliases are
# cleared: wrkq refuses a WRKQ_DB_PATH/WRKQ_DB_PATH_FILE that disagrees with
# WRKQ_DB (T-08302). Without wrkqadm the path stays unmigrated and wrkq refuses
# fast, which the suites tolerate.
provision_wrkq() {
  if command -v wrkqadm >/dev/null 2>&1; then
    WRKQ_DB="${WRKQ_DB_FILE}" wrkqadm migrate >/dev/null \
      || die "could not migrate the ephemeral wrkq ledger at ${WRKQ_DB_FILE}"
  else
    log "wrkqadm not found; ${WRKQ_DB_FILE} stays unmigrated and wrkq will refuse"
  fi
}

# Every project id the suites resolve by marker scan. A fixture project is an
# empty canonical checkout (a directory with its own .git) under the
# environment's own search root, so placement never resolves the operator's
# live checkouts under ~/praesidium (T-10161).
FIXTURE_PROJECTS=(
  hrc-runtime agent-spaces agent-control-plane wrkq taskboard foundry ghostmux arris
)

provision_projects() {
  PROJECT_SEARCH_ROOT="${ROOT}/projects"
  local project
  for project in "${FIXTURE_PROJECTS[@]}"; do
    # A hook exports GIT_DIR and kin; they would aim git at the outer checkout.
    # Check repository health, not the .git directory: macOS's periodic /tmp
    # sweep deletes HEAD, config and objects from a long-lived root while the
    # directories survive (T-10646). Re-running init on a gutted .git repairs it.
    env -u GIT_DIR -u GIT_WORK_TREE -u GIT_INDEX_FILE -u GIT_COMMON_DIR \
      git -C "${PROJECT_SEARCH_ROOT}/${project}" rev-parse --git-dir 2>/dev/null | grep -qx .git && continue
    mkdir -p "${PROJECT_SEARCH_ROOT}/${project}"
    env -u GIT_DIR -u GIT_WORK_TREE -u GIT_INDEX_FILE -u GIT_COMMON_DIR \
      git init -q "${PROJECT_SEARCH_ROOT}/${project}"
  done
}

# What the running daemon was started from. A daemon is reused only when both
# match: its ledger and its project search root. (The post-push runner tears the
# environment down before each verify, so it never serves an earlier push's code.)
daemon_fingerprint() {
  printf '%s\n%s\n' "${WRKQ_DB_FILE}" "${PROJECT_SEARCH_ROOT}"
}

# -- Ownership (T-10329) -------------------------------------------------------
#
# A daemon lives exactly as long as something owns it. Before this, `up` started
# the daemon with nohup and exited, so every daemon was reparented to launchd and
# lived until someone ran `down` in the same root. A runner killed mid-gate, or a
# scratch clone deleted after its run, left one behind for good (five on max3 on
# 2026-10-05, blocking `hrc admin release sweep` on a 97% disk).
#
# <root>/owners holds one line per owner:
#   pid:<pid> <lstart>   a run that needs the daemon (`up --owner <pid>`; the
#                        verify/e2e recipes pass their own shell). lstart guards
#                        against pid reuse.
#   operator             a bare `up`: deliberately left up until `down`.
# <root>/repo records the checkout. The daemon is owned while that checkout
# exists and either an operator line is present or some pid owner is alive.
#
# Two mechanisms enforce it. A watchdog, started in its own session beside each
# daemon, stops the daemon (and its tmux server) within WATCH_INTERVAL of it
# becoming unowned — normal exit, failure, SIGINT, SIGKILL of the owner, or the
# checkout being deleted. Every `up` also reaps any dev-env root of this uid
# whose daemon is unowned, in case a watchdog itself was killed.

proc_start() { ps -o lstart= -p "$1" 2>/dev/null | sed 's/^ *//;s/ *$//'; }

# True when the pid is alive AND is still the process that was recorded.
pid_line_alive() {
  local pid="$1" lstart="$2"
  kill -0 "${pid}" 2>/dev/null || return 1
  [[ "$(proc_start "${pid}")" == "${lstart}" ]]
}

# root_owned <root>: is anything still entitled to that root's daemon?
root_owned() {
  local root="$1" repo line pid lstart
  [[ -f "${root}/owners" ]] || return 1
  repo="$(cat "${root}/repo" 2>/dev/null || true)"
  [[ -n "${repo}" && -d "${repo}" ]] || return 1
  while IFS= read -r line || [[ -n "${line}" ]]; do
    case "${line}" in
      operator) return 0 ;;
      pid:*)
        line="${line#pid:}"
        pid="${line%% *}"
        lstart="${line#* }"
        pid_line_alive "${pid}" "${lstart}" && return 0
        ;;
    esac
  done < "${root}/owners"
  return 1
}

add_owner() {
  local owner="$1" line
  if [[ -z "${owner}" ]]; then
    line="operator"
  else
    kill -0 "${owner}" 2>/dev/null || die "--owner ${owner} is not a live process"
    line="pid:${owner} $(proc_start "${owner}")"
  fi
  # repo first: a reap that sees an owners file must also see the checkout.
  printf '%s\n' "${REPO_ROOT}" > "${REPO_FILE}"
  grep -qxF "${line}" "${OWNERS_FILE}" 2>/dev/null || printf '%s\n' "${line}" >> "${OWNERS_FILE}"
}

# Only ever signal a pid that is still an `hrc ... server serve` process: pid
# files outlive their processes, and the number may since belong to anything.
is_serve_pid() {
  [[ -n "$1" ]] && ps -o command= -p "$1" 2>/dev/null | grep -q 'hrc.js server serve'
}

# stop_root <root>: stop_daemon for an arbitrary root.
stop_root() {
  local root="$1" pid wpid
  pid="$(cat "${root}/daemon.pid" 2>/dev/null || true)"
  if is_serve_pid "${pid}"; then
    kill "${pid}" 2>/dev/null || true
    local waited=0
    while (( waited < 10 )) && kill -0 "${pid}" 2>/dev/null; do
      sleep 1
      waited=$((waited + 1))
    done
    kill -9 "${pid}" 2>/dev/null || true
  fi
  rm -f "${root}/daemon.pid"
  # The daemon owns a tmux server on its own socket; killing the daemon does not
  # reap it, and a leaked tmux server keeps panes (and their processes) alive.
  if [[ -S "${root}/run/tmux.sock" ]]; then
    tmux -S "${root}/run/tmux.sock" kill-server 2>/dev/null || true
  fi
  rm -f "${root}/run/hrc.sock" "${root}/run/server.lock" "${root}/run/server.pid" 2>/dev/null || true
  # Last, and never ourselves: the watchdog calls this too.
  wpid="$(cat "${root}/watchdog.pid" 2>/dev/null || true)"
  if [[ -n "${wpid}" && "${wpid}" != "$$" ]] && ps -o command= -p "${wpid}" 2>/dev/null | grep -q 'dev-env.sh watch'; then
    kill "${wpid}" 2>/dev/null || true
  fi
  rm -f "${root}/watchdog.pid"
}

# Reap every dev-env root of this uid whose daemon nothing owns. Both bases are
# scanned: roots made before the base was normalized live under TMPDIR. A root
# with a daemon.pid but no owners file was made by the pre-T-10329 script, whose
# daemons nothing ever owned. A root whose checkout is gone is removed outright.
reap_unowned_roots() {
  local base root repo
  for base in "${ROOT_BASE}" "${TMPDIR:-/tmp}"; do
    base="${base%/}"
    for root in "${base}/${ROOT_PREFIX}"*; do
      [[ -d "${root}" ]] || continue
      [[ "$(cd "${root}" && pwd -P)" == "$(cd "${ROOT}" 2>/dev/null && pwd -P || echo "${ROOT}")" ]] && continue
      if [[ -f "${root}/owners" ]]; then
        root_owned "${root}" && continue
        repo="$(cat "${root}/repo" 2>/dev/null || true)"
        if [[ -f "${root}/daemon.pid" || -S "${root}/run/tmux.sock" ]]; then
          log "reaping unowned dev-env daemon in ${root} (checkout ${repo:-unknown})"
          stop_root "${root}"
        fi
        if [[ -z "${repo}" || ! -d "${repo}" ]]; then
          log "removing dev-env root of a deleted checkout: ${root}"
          rm -rf "${root}"
        fi
      elif [[ -f "${root}/daemon.pid" ]]; then
        log "reaping pre-ownership dev-env root ${root}"
        stop_root "${root}"
        rm -rf "${root}"
      fi
    done
  done
}

# The watchdog for one daemon. It runs detached in its own session so a process
# group kill aimed at the runner does not take it down with the daemon, and it
# only ever acts on the daemon pid it was started for.
cmd_watch() {
  local dpid="$1"
  trap '' INT HUP
  printf '%s\n' "$$" > "${WATCHDOG_PID_FILE}"
  log "watching daemon pid ${dpid} for ${ROOT} ($(date -u +%FT%TZ))"
  while :; do
    sleep "${WATCH_INTERVAL}"
    [[ "$(cat "${PID_FILE}" 2>/dev/null || true)" == "${dpid}" ]] || { log "daemon ${dpid} replaced; exiting"; exit 0; }
    if ! kill -0 "${dpid}" 2>/dev/null; then
      log "daemon ${dpid} exited; clearing its residue ($(date -u +%FT%TZ))"
      stop_root "${ROOT}"
      exit 0
    fi
    if ! root_owned "${ROOT}"; then
      log "daemon ${dpid} is unowned; stopping it ($(date -u +%FT%TZ))"
      stop_root "${ROOT}"
      exit 0
    fi
  done
}

watchdog_alive() {
  local wpid
  wpid="$(cat "${WATCHDOG_PID_FILE}" 2>/dev/null || true)"
  [[ -n "${wpid}" ]] && ps -o command= -p "${wpid}" 2>/dev/null | grep -q 'dev-env.sh watch'
}

start_watchdog() {
  local dpid="$1" self="${REPO_ROOT}/scripts/dev-env.sh"
  # perl's setsid is the portable one: macOS ships no setsid(1).
  HRC_DEV_ENV_ROOT="${ROOT}" nohup perl -MPOSIX -e 'POSIX::setsid(); exec @ARGV or die "exec: $!"' \
    bash "${self}" watch "${dpid}" </dev/null >>"${WATCHDOG_LOG}" 2>&1 &
  local waited=0
  while (( waited < 50 )) && ! watchdog_alive; do
    sleep 0.1
    waited=$((waited + 1))
  done
  watchdog_alive || die "dev-env watchdog did not start; see ${WATCHDOG_LOG}"
}

start_daemon() {
  # A daemon started before it was pointed at the environment's own ledger
  # still reaches the operator's; reusing it would keep half the environment
  # on production state, so it is replaced rather than reused. A daemon is
  # reused only while its watchdog stands, so ownership stays enforced.
  if daemon_responds; then
    if [[ "$(cat "${DAEMON_WRKQ_FILE}" 2>/dev/null || true)" == "$(daemon_fingerprint)" ]] && watchdog_alive; then
      log "daemon already healthy on ${SOCKET} (reused)"
      return 0
    fi
    log "replacing daemon started from another ledger or project root, or without a watchdog"
    stop_daemon
  fi

  # Reaching here with files present means the previous daemon died or was
  # killed without teardown. Clear the residue rather than failing on it.
  if [[ -e "${SOCKET}" || -f "${PID_FILE}" ]]; then
    log "clearing stale daemon residue under ${RUN_DIR}"
    stop_daemon
  fi

  mkdir -p "${RUN_DIR}" "${STATE_DIR}"
  log "starting ephemeral daemon (hrc server serve) → ${LOG_FILE}"
  (
    cd "${REPO_ROOT}"
    HRC_RUNTIME_DIR="${RUN_DIR}" HRC_STATE_DIR="${STATE_DIR}" ASP_AGENTS_ROOT="${AGENTS_DIR}" \
      HRC_PROJECT_SEARCH_ROOTS="${PROJECT_SEARCH_ROOT}" \
      HRC_WRKQ_DB="${WRKQ_DB_FILE}" HRC_WRKQD_TOKEN_FILE='' WRKQ_DB="${WRKQ_DB_FILE}" \
      nohup env -u WRKQ_DB_PATH -u WRKQ_DB_PATH_FILE bun "${REPO_ROOT}/packages/hrc-cli/bin/hrc.js" server serve \
      >"${LOG_FILE}" 2>&1 &
    printf '%s\n' "$!" > "${PID_FILE}"
    daemon_fingerprint > "${DAEMON_WRKQ_FILE}"
  )

  start_watchdog "$(cat "${PID_FILE}")"

  local waited=0
  while (( waited < 60 )); do
    daemon_responds && { log "daemon healthy (pid $(cat "${PID_FILE}"))"; return 0; }
    sleep 1
    waited=$((waited + 1))
  done
  tail -20 "${LOG_FILE}" >&2 || true
  die "ephemeral daemon did not become healthy within ${waited}s"
}

# Teardown is unconditional and never fails: it has to work on a half-created
# root, on a root whose daemon is already gone, and on a root that a previous
# crashed env-down left behind.
stop_daemon() { stop_root "${ROOT}"; }

cmd_up() {
  mkdir -p "${ROOT}" "${RUN_DIR}" "${STATE_DIR}" "${AGENTS_DIR}"
  # Own the root first, so neither its watchdog nor a reap from another
  # checkout takes a reusable daemon here for an orphan during the build.
  add_owner "${OWNER_PID}"
  reap_unowned_roots
  provision_build
  provision_projects
  provision_agents
  provision_wrkq
  start_daemon
  write_env_file

  log "environment ready"
  log "  root         ${ROOT}"
  log "  runtime dir  ${RUN_DIR}   (HRC_RUNTIME_DIR)"
  log "  state dir    ${STATE_DIR}   (HRC_STATE_DIR)"
  log "  agents root  ${AGENTS_DIR}   (ASP_AGENTS_ROOT, ${#FIXTURE_AGENTS[@]} fixture homes)"
  log "  wrkq ledger  ${WRKQ_DB_FILE}   (WRKQ_DB)"
  log "  projects     ${PROJECT_SEARCH_ROOT}   (HRC_PROJECT_SEARCH_ROOTS, ${#FIXTURE_PROJECTS[@]} fixture checkouts)"
  log "  daemon       ${SOCKET}  pid $(cat "${PID_FILE}" 2>/dev/null || echo '?')"
  log "  daemon log   ${LOG_FILE}"
  log "  owners       ${OWNERS_FILE}   ($(paste -sd, "${OWNERS_FILE}"); watchdog pid $(cat "${WATCHDOG_PID_FILE}" 2>/dev/null || echo '?'))"
  log "  env file     ${ENV_FILE}   (source it to point a shell here)"
}

cmd_down() {
  if [[ ! -d "${ROOT}" ]]; then
    log "nothing to tear down (${ROOT} absent)"
    return 0
  fi
  stop_daemon
  rm -rf "${ROOT}"
  log "environment removed (${ROOT})"
}

# Print the exports so a caller can `eval "$(scripts/dev-env.sh env)"` without
# knowing where the root landed.
cmd_env() {
  [[ -f "${ENV_FILE}" ]] || die "no environment provisioned; run 'just env-up' first"
  cat "${ENV_FILE}"
}

# `up` takes `--owner <pid>`: the daemon then lives only while that process
# does (or until another owner's lease ends). Without it, `up` is the operator
# deliberately leaving the daemon up until `down`.
OWNER_PID=""
case "${1:-}" in
  up)
    if [[ "${2:-}" == "--owner" ]]; then
      [[ "${3:-}" =~ ^[0-9]+$ ]] || die "usage: dev-env.sh up [--owner <pid>]"
      OWNER_PID="$3"
    elif [[ -n "${2:-}" ]]; then
      die "usage: dev-env.sh up [--owner <pid>]"
    fi
    cmd_up
    ;;
  down)  cmd_down ;;
  env)   cmd_env ;;
  watch) [[ "${2:-}" =~ ^[0-9]+$ ]] || die "usage: dev-env.sh watch <daemon-pid>"; cmd_watch "$2" ;;
  *)     die "usage: dev-env.sh <up [--owner <pid>]|down|env>" ;;
esac
