import packageJson from '../package.json' with { type: 'json' }

export const HRC_API_VERSION = packageJson.version

export { HRC_TASK_CLAIM_CREDENTIAL_FILE_ENV } from './federation.js'

export { environmentWithoutGitOverrides } from './git-environment.js'

export {
  expandRegistryHome,
  findWrkqProjectEntry,
  readWrkqProjectRegistry,
} from './project-registry.js'
export type { WrkqProjectRegistryEntry } from './project-registry.js'

export {
  HrcBadRequestError,
  HrcConflictError,
  HrcDomainError,
  HrcErrorCode,
  HrcInternalError,
  HrcNotFoundError,
  HrcRuntimeUnavailableError,
  HrcUnprocessableEntityError,
  createHrcError,
  httpStatusForErrorCode,
} from './errors.js'
export type { HrcHttpError, HrcHttpStatus } from './errors.js'

export {
  formatCanonicalScopeRef,
  formatCanonicalSessionRef,
  formatSelector,
  isCodexAppOwnedScopeRef,
  isConcreteSelector,
  isStableSelector,
  normalizeSessionRef,
  parseSelector,
  splitSessionRef,
} from './selectors.js'
export type {
  HrcConcreteSelector,
  HrcHostSelector,
  HrcMessageSelector,
  HrcMessageSeqSelector,
  HrcMonitorSelector,
  ParseSelectorOptions,
  HrcRuntimeSelector,
  HrcScopeSelector,
  HrcSelector,
  HrcSessionRef,
  HrcSessionSelector,
  HrcStableSelector,
  HrcTargetSelector,
} from './selectors.js'

export { parseFence, validateFence } from './fences.js'
export type {
  HrcActiveSessionState,
  HrcFence,
  HrcFenceValidationFailure,
  HrcFenceValidationResult,
  HrcFenceValidationSuccess,
} from './fences.js'

export {
  resolveControlSocketPath,
  resolveDatabasePath,
  resolveIngestSocketPath,
  resolveLaunchesDir,
  resolveMigrationsDir,
  resolveRuntimeRoot,
  resolveSpoolDir,
  resolveStateRoot,
  resolveTmuxSocketPath,
} from './paths.js'
export {
  getHrcCliRpcMetricsHook,
  installCliMetricsRecorder,
  recordCliLaunch,
} from './cli-metrics.js'
export type {
  CliLaunchMetricRecord,
  CliLaunchPhase,
  CliMetricsRecorder,
  HrcCliRpcMetric,
  HrcCliRpcMetricsHook,
} from './cli-metrics.js'
export {
  BROKER_TO_HRC_LIFECYCLE_POLICY_HASH,
  BROKER_TO_HRC_LIFECYCLE_POLICY_ID,
  BROKER_TO_HRC_LIFECYCLE_KIND,
  BROKER_TO_HRC_LIFECYCLE_POLICY_VERSION,
  brokerToHrcLifecyclePolicyHash,
  lifecycleKindForBrokerEvent,
} from './broker-lifecycle-policy.js'

export {
  TOOL_RESULT_SPILL_HEAD_CHARS,
  TOOL_RESULT_SPILL_TAIL_CHARS,
  TOOL_RESULT_SPILL_THRESHOLD_BYTES,
  brokerToolResultBlobId,
  createToolResultSpillStub,
  lifecycleToolResultBlobId,
  readToolResultSpillDescriptor,
  toolResultExceedsSpillThreshold,
  toolResultFromBrokerResult,
} from './tool-result-storage.js'
export type {
  CanonicalToolResult,
  CanonicalToolResultContentBlock,
  ToolResultBlobKind,
  ToolResultSpillDescriptor,
} from './tool-result-storage.js'

export type {
  HrcAppCommandSessionSpec,
  HrcAppHarnessSessionSpec,
  HrcAppSessionRecord,
  HrcAppSessionRef,
  HrcAppSessionSpec,
  HrcActuatorSplitAuthorityView,
  HrcActuatorSplitPolicy,
  HrcApprovedMutationRef,
  HrcRuntimeKind,
  HrcCapabilityStatus,
  HrcAspToolchainBinaryKind,
  HrcAspToolchainHelloObservation,
  HrcAspToolchainStatus,
  HrcCommandLaunchSpec,
  HrcContinuityRecord,
  HrcContinuationRef,
  HrcDispatchOrigin,
  HrcDispatchOriginKind,
  HrcEventCategory,
  HrcEventTail,
  HrcEventEnvelope,
  HrcEventSource,
  HrcExecutionIntent,
  HrcExecutionMode,
  HrcHarness,
  HrcHarnessIntent,
  HrcHookBridgeConfig,
  HrcIoMode,
  HrcLifecycleEvent,
  HrcBoundedEventStreamRecord,
  HrcLifecyclePolicyRecord,
  HrcLifecycleTransport,
  HrcLaunchArtifact,
  HrcLaunchPromptMaterial,
  HrcLaunchEnvConfig,
  HrcLaunchRecord,
  HrcLocalBridgeRecord,
  HrcManagedSessionKind,
  HrcManagedSessionRecord,
  HrcProvider,
  HrcRuntimeControllerKind,
  HrcRuntimeOperationKind,
  HrcRuntimeOperationStatus,
  HrcBrokerInvocationState,
  HrcBrokerEventProjectionStatus,
  HrcCompiledRuntimePlanRecord,
  HrcRuntimeOperationRecord,
  HrcBrokerInvocationRecord,
  HrcBrokerInvocationEventRecord,
  HrcRuntimeArtifactRecord,
  HrcPermissionDecisionRecord,
  HrcReleaseStatus,
  HrcRunRecord,
  HrcSurfaceBindingRecord,
  HrcTaskContext,
  HrcTurnResponseFormat,
  HrcPresentationIntent,
  HrcRuntimeIntent,
  HrcRuntimeSnapshot,
  HrcSessionRecord,
  HrcStatusActiveRuntimeView,
  HrcStatusResponse,
  HrcStatusSummaryResponse,
  HrcStatusSessionView,
  HrcStatusTmuxView,
  PraesidiumBuild,
  PraesidiumReleaseManifest,
} from './contracts.js'
export {
  HRC_ARTIFACT_REPORTED_EVENT,
  HRC_PROVIDER_TRANSCRIPT_ARTIFACT_KIND,
  HRC_PROVIDER_TRANSCRIPT_ARTIFACT_MEDIA_TYPE,
  HRC_PROVIDER_TRANSCRIPT_ARTIFACT_SCHEMA,
  HRC_PROVIDER_TRANSCRIPT_ARTIFACT_STORAGE_KIND,
  HRC_PROVIDER_TRANSCRIPT_REPORTED_EVENT,
} from './contracts.js'
export type {
  HrcProviderTranscriptArtifactMetadata,
  HrcProviderTranscriptReportedPayload,
} from './contracts.js'
export {
  HRC_FIRST_TURN_MISSING_BUNDLE_ARTIFACT_KIND,
  HRC_FIRST_TURN_MISSING_BUNDLE_SCHEMA,
  HRC_FIRST_TURN_MISSING_DIAGNOSTICS_EVENT,
  HRC_FIRST_TURN_MISSING_EVENT,
  HRC_FIRST_TURN_MISSING_LATE_START_EVENT,
} from './contracts.js'
export type {
  GetFirstTurnDiagnosticsResponse,
  HrcFirstTurnDiagnosticsTrip,
  HrcFirstTurnMissingBundle,
  HrcFirstTurnWatchRecord,
  HrcRuntimeHealthDetail,
  ListFirstTurnDiagnosticsResponse,
} from './contracts.js'

export {
  HRC_RUNTIME_PRESENTATION_EVENT,
  HRC_SESSION_RETITLED_EVENT,
} from './contracts.js'
export type {
  HrcPresentationRuntimeRow,
  HrcPresentationTmuxTarget,
  HrcRuntimePresentationEventPayload,
  HrcRuntimePresentationRecord,
  HrcSessionRetitledEventPayload,
  ListPresentationRuntimesResponse,
} from './contracts.js'

export type {
  ApplyAppManagedSessionInput,
  ApplyAppManagedSessionsRequest,
  ApplyAppManagedSessionsResponse,
  ApplyAppSessionInput,
  ApplyAppSessionsRequest,
  ApplyAppSessionsResponse,
  AppSessionFreshnessFence,
  AttachRuntimeRequest,
  AttachRuntimeResponse,
  BindSurfaceRequest,
  BrokerInspectRequest,
  BrokerForensicsEvent,
  BrokerForensicsResponse,
  HrcBrokerIngestItem,
  HrcEventIngestAck,
  HrcEventIngestBatch,
  HrcEventIngestFeed,
  HrcLifecycleIngestItem,
  HrcToolResultBlobPart,
  BrokerInspectResponse,
  FinalSummaryRecoveryResult,
  FinalSummaryRecoveryState,
  OperatorInspectSource,
  CaptureResponse,
  ClearContextRequest,
  ClearContextResponse,
  RegistrationGcCandidate,
  ListRegistrationGcCandidatesResponse,
  RetireRegistrationScopesRequest,
  RegistrationGcResult,
  RetireRegistrationScopesResponse,
  CloseBridgeRequest,
  ActiveRunContributionCapability,
  ActiveRunContributionCapabilityReason,
  DeliverBridgeRequest,
  DeliverBridgeResponse,
  DispatchTurnRequest,
  DispatchTurnResponse,
  DispatchTurnTerminalOutcome,
  DropContinuationRequest,
  DropContinuationResponse,
  EnsureAppSessionDryRunPlan,
  EnsureAppSessionRequest,
  EnsureAppSessionResponse,
  EnsureRuntimeRequest,
  HrcAppSessionFilter,
  EnsureRuntimeResponse,
  LaunchCommandScopedRunBinding,
  LaunchCommandScopedRunRequest,
  LaunchCommandScopedRunResponse,
  StartRuntimeRequest,
  StartRuntimeResponse,
  ExactStartRuntimeRequest,
  StartRuntimeRosterClaim,
  SuffixStartRuntimeRequest,
  EnsureWindowRequest,
  EnsureWindowResponse,
  HealthResponse,
  HrcAttachDescriptor,
  HrcActiveRunContributionRequest,
  HrcActiveRunContributionResponse,
  HrcBridgeDeliverTextRequest,
  HrcBridgeDeliverTextResponse,
  HrcSubscriberAdmissionEntry,
  HrcSubscriberAdmissionRoute,
  HrcSubscriberAdmissionSnapshot,
  HrcSubscriberReceiptAckRequest,
  HrcSubscriberReceiptAckResponse,
  HrcSubscriberReceiptMode,
  HrcSubscriberReceiptState,
  HrcTurnAdmissionCloseRequest,
  HrcTurnAdmissionReopenRequest,
  HrcTurnAdmissionState,
  HrcBridgeTargetSelector,
  HrcBridgeTargetRequest,
  HrcBridgeTargetResponse,
  InterruptAppSessionRequest,
  InspectRuntimeRequest,
  InspectRuntimeResponse,
  KillBrokerTmuxLeasesResponse,
  ListAppSessionsRequest,
  OpenBrokerSessionRequest,
  OpenBrokerSessionResponse,
  RegisterBridgeTargetRequest,
  RegisterBridgeTargetResponse,
  RemoveAppSessionRequest,
  RemoveAppSessionResponse,
  ResolveSessionRequest,
  ResolveSessionResponse,
  RestartStyle,
  ReconcileActiveRunReason,
  ReconcileActiveRunResult,
  ReconcileActiveRunsRequest,
  ReconcileActiveRunsResponse,
  ReconcileActiveRunsSummary,
  OperatorAttachDescriptor,
  PrepareAttachedRunRequest,
  PrepareAttachedRunResponse,
  ResumeAttachedRunRequest,
  ResumeAttachedRunResponse,
  ResumeContinuationRequest,
  ResumeContinuationResponse,
  SendLiteralInputRequest,
  SendLiteralInputResponse,
  SendWindowLiteralInputRequest,
  StatusResponse,
  StatusSummaryResponse,
  SummonIntent,
  PruneRuntimeResult,
  PruneRuntimesRequest,
  PruneRuntimesResponse,
  RuntimePruneDeleteCounts,
  PruneRuntimesSummary,
  SweepRuntimeResult,
  SweepZombieRunResult,
  SweepZombieRunsRequest,
  SweepZombieRunsResponse,
  SweepZombieRunsSummary,
  SweepRuntimesRequest,
  SweepRuntimesResponse,
  SweepRuntimesSummary,
  SweepRuntimeTransport,
  TerminateRuntimeRequest,
  TerminateRuntimeResponse,
  TerminateAppSessionRequest,
  RuntimeActionResponse,
  UnbindSurfaceRequest,
  DispatchAppHarnessTurnRequest,
  DispatchAppHarnessTurnResponse,
  SendAppHarnessInFlightInputRequest,
  SendAppHarnessInFlightInputResponse,
  ClearAppSessionContextRequest,
  ClearAppSessionContextResponse,
} from './http-contracts.js'
export {
  OPERATOR_REAP_REASON,
  isExactStartRuntimeRequest,
  isSuffixStartRuntimeRequest,
} from './http-contracts.js'

export {
  HRC_QUEUED_BEHIND_BUSY_TURN_WARNING,
  HRC_QUEUED_TO_LIVE_HARNESS_WARNING,
  HRC_STARTED_FRESH_TURN_OUTCOME,
  hrcAdmittedIntoActiveTurn,
  hrcPresentedToLiveHarness,
} from './delivery-contracts.js'
export type {
  HrcDeliveryOutcome,
  HrcDeliveryWarning,
  HrcSteerContributionRecord,
  HrcSteerContributionState,
} from './delivery-contracts.js'

export type {
  HrcMessageAddress,
  HrcTargetState,
  TargetCapabilityView,
  HrcTargetRuntimeView,
  HrcTargetAmbiguityCandidateView,
  HrcTargetView,
  HrcMessageKind,
  HrcMessagePhase,
  HrcMessageExecutionState,
  HrcMessageExecution,
  HrcMessageRecord,
  HrcMessageDeliveryEvidence,
  HrcCollectiveHistoryObservation,
  HrcCollectiveMessageRecord,
  HrcMessageHistoryStatus,
  HrcMessageFilter,
  HrcDirectiveOnlyIntent,
  HrcDmRuntimeIntent,
  EnsureTargetRequest,
  EnsureTargetResponse,
  ListTargetsRequest,
  GetTargetRequest,
  DispatchTurnBySelectorRequest,
  DispatchTurnBySelectorResponse,
  DeliverLiteralBySelectorRequest,
  DeliverLiteralBySelectorResponse,
  CaptureBySelectorRequest,
  CaptureBySelectorResponse,
  CreateMessageRequest,
  CreateMessageResponse,
  ListMessagesRequest,
  ListMessagesResponse,
  TraceMessageRequest,
  HrcMessageTraceAcceptance,
  HrcMessageTraceDestination,
  HrcMessageTraceVerdict,
  TraceMessageResponse,
  WatchMessagesRequest,
  WaitMessageRequest,
  WaitMessageResponse,
  SemanticDmRequest,
  SemanticDmResponse,
  SemanticTurnHandoffRequest,
  SemanticTurnHandoffStartedResponse,
  SemanticTurnHandoffPendingResponse,
  SemanticTurnHandoffResponse,
} from './hrcchat-contracts.js'

export {
  HRC_MAIL_REPLY_SCHEMA_DIALECT,
  HRC_MAIL_REPLY_SCHEMA_MAX_BYTES,
} from './hrcmail-contracts.js'
export type {
  HrcMailAckRequest,
  HrcMailAckResponse,
  HrcMailActor,
  HrcMailCatRequest,
  HrcMailCatResponse,
  HrcMailDeferRequest,
  HrcMailDeferResponse,
  HrcMailDispositionOutcome,
  HrcMailDispositionResult,
  HrcMailEnvelope,
  HrcMailEnvelopeState,
  HrcMailInboxRequest,
  HrcMailInboxResponse,
  HrcMailIngressPath,
  HrcMailListRequest,
  HrcMailListResponse,
  HrcMailPayload,
  HrcMailPayloadKind,
  HrcMailReceipt,
  HrcMailReplySchema,
  HrcMailSendRequest,
  HrcMailSendResponse,
} from './hrcmail-contracts.js'

export {
  buildHrcInvocationExposure,
  canonicalCorrelationJson,
  correlationConflicts,
  normalizeCorrelation,
  selectorFor,
  sessionRefFor,
} from './invocation-exposure.js'
export type {
  BuildHrcInvocationExposureInput,
  HrcInvocationExposure,
  HrcRunCorrelation,
} from './invocation-exposure.js'
export { createMonitorConditionEngine } from './monitor/condition-engine.js'
export {
  createMonitorReader,
  isImmediateRoleChildScopeRef,
  isResolutionError,
  monitorEventMatchesSelector,
  monitorSessionMatchKind,
} from './monitor/index.js'
export { MONITOR_EXIT_CODES } from './monitor/exit-codes.js'
export type { MonitorExitCode } from './monitor/exit-codes.js'
export { RUNTIME_STATUS_LEVEL_BY_STATUS } from './monitor/status-levels.js'
export type { HrcRuntimeStatusLevel } from './monitor/status-levels.js'
export type {
  HrcMonitorCondition,
  HrcMonitorConditionEngine,
  HrcMonitorConditionEngineReader,
  HrcMonitorConditionOutcome,
  HrcMonitorConditionResult,
  HrcMonitorConditionWaitRequest,
  HrcMonitorContextChangedReason,
  HrcMonitorFailureKind,
  HrcMonitorOutcome,
} from './monitor/condition-engine.js'
export type {
  HrcMonitorCapture,
  HrcMonitorCaptureOptions,
  HrcMonitorEvent,
  HrcMonitorMessageState,
  HrcMonitorMatchedRuntime,
  HrcMonitorResolution,
  HrcMonitorResolutionResult,
  HrcMonitorResolvedSelector,
  HrcMonitorRuntimeState,
  HrcMonitorSessionState,
  HrcMonitorSnapshot,
  HrcMonitorState,
  HrcMonitorWatchRequest,
} from './monitor/index.js'

export type {
  BirthDesignationEstablishmentDecision,
  BirthDesignationProvenance,
  BirthDesignationRecord,
  BirthDesignationResult,
  BirthDesignationState,
  BirthDesignationSupersededBy,
  FederationGateModeValue,
  FederationExpectedPlacement,
  FederationInteractiveLifecycleSignal,
  FederationSemanticTurnIdentity,
  FederationSemanticTurnSignal,
  FederationMailPayload,
  FederationMessageDelivery,
  FederationMessageEnvelope,
  FederationPendingMessageEnvelope,
  FederationPlacementBinding,
  FederationNodeRuntimeProjection,
  FederationOutboxDeliveryRecord,
  FederationOutboxError,
  FederationOutboxState,
  FederationPeerCapabilities,
  FederationPeerHealthObservation,
  FederationRemoteEstablishRequest,
  FederationRemoteEstablishResult,
  FederationRetirementOutcome,
  FederationRetirementRequest,
  FederationRetirementResult,
  FederationRetirementState,
  FederationRuntimeProjectionReport,
  LedgerSkewScan,
  LocateAuthority,
  LocateBindingRecord,
  LocateBindingsReport,
  LocateDeclaredPolicy,
  LocateDesignationView,
  LocateLedgerView,
  LocateNote,
  LocateObservation,
  LocateObservedRuntime,
  LocatePeerResolution,
  LocateRegistryView,
  LocateRetirement,
  LocateSkew,
  ScopeLocation,
} from './federation-contracts.js'

/**
 * Runtime-intent assembly from a resolved agent placement (T-07615 moved this
 * here from hrc-sdk). It lives in hrc-core because the DAEMON needs it too:
 * the wrkq kicker must birth a target the ledger addressed, and wrkq stores
 * only the verbatim `+node=`/`+model=` directive block, never an intent. A
 * server reaching into the client SDK to assemble one would be backwards.
 */
export {
  applyProvisionDirectives,
  buildHrcRuntimeIntent,
  harnessFrontendToHrcHarness,
  resolveAgentHarness,
} from './runtime-intent-assembly.js'
export type {
  BuildHrcRuntimeIntentInput,
  ResolvedAgentHarness,
} from './runtime-intent-assembly.js'
