import packageJson from '../package.json' with { type: 'json' }

export const HRC_API_VERSION = packageJson.version

export {
  HrcBadRequestError,
  HrcConflictError,
  HrcDomainError,
  HrcErrorCode,
  HrcInternalError,
  HrcNotFoundError,
  HrcRuntimeUnavailableError,
  HrcUnprocessableEntityError,
  createHrcError,
  httpStatusForErrorCode,
} from './errors.js'
export type { HrcHttpError, HrcHttpStatus } from './errors.js'

export {
  isConcreteSelector,
  isStableSelector,
  normalizeSessionRef,
  parseSelector,
  splitSessionRef,
} from './selectors.js'
export type {
  HrcConcreteSelector,
  HrcSelector,
  HrcSessionRef,
  HrcStableSelector,
} from './selectors.js'

export { parseFence, validateFence } from './fences.js'
export type {
  HrcActiveSessionState,
  HrcFence,
  HrcFenceValidationFailure,
  HrcFenceValidationResult,
  HrcFenceValidationSuccess,
} from './fences.js'

export {
  resolveControlSocketPath,
  resolveDatabasePath,
  resolveLaunchesDir,
  resolveMigrationsDir,
  resolveRuntimeRoot,
  resolveSpoolDir,
  resolveStateRoot,
  resolveTmuxSocketPath,
} from './paths.js'

export type {
  HrcAppCommandSessionSpec,
  HrcAppHarnessSessionSpec,
  HrcAppSessionRecord,
  HrcAppSessionRef,
  HrcAppSessionSpec,
  HrcRuntimeKind,
  HrcCapabilityStatus,
  HrcCommandLaunchSpec,
  HrcContinuityRecord,
  HrcContinuationRef,
  HrcEventCategory,
  HrcEventEnvelope,
  HrcEventSource,
  HrcExecutionIntent,
  HrcExecutionMode,
  HrcHarness,
  HrcHarnessIntent,
  HrcHookBridgeConfig,
  HrcIoMode,
  HrcLifecycleEvent,
  HrcLifecycleTransport,
  HrcLaunchArtifact,
  HrcLaunchEnvConfig,
  HrcLaunchRecord,
  HrcLocalBridgeRecord,
  HrcManagedSessionKind,
  HrcManagedSessionRecord,
  HrcProvider,
  HrcRunRecord,
  HrcSurfaceBindingRecord,
  HrcTaskContext,
  HrcRuntimeIntent,
  HrcRuntimeSnapshot,
  HrcSessionRecord,
  HrcStatusActiveRuntimeView,
  HrcStatusResponse,
  HrcStatusSessionView,
  HrcStatusTmuxView,
} from './contracts.js'

export type {
  ApplyAppManagedSessionInput,
  ApplyAppManagedSessionsRequest,
  ApplyAppManagedSessionsResponse,
  ApplyAppSessionInput,
  ApplyAppSessionsRequest,
  ApplyAppSessionsResponse,
  AppSessionFreshnessFence,
  AttachRuntimeRequest,
  AttachRuntimeResponse,
  BindSurfaceRequest,
  CaptureResponse,
  ClearContextRequest,
  ClearContextResponse,
  CloseBridgeRequest,
  DeliverBridgeRequest,
  DeliverBridgeResponse,
  DispatchTurnRequest,
  DispatchTurnResponse,
  EnsureAppSessionDryRunPlan,
  EnsureAppSessionRequest,
  EnsureAppSessionResponse,
  EnsureRuntimeRequest,
  HrcAppSessionFilter,
  EnsureRuntimeResponse,
  StartRuntimeRequest,
  StartRuntimeResponse,
  EnsureWindowRequest,
  EnsureWindowResponse,
  HealthResponse,
  HrcAttachDescriptor,
  HrcBridgeDeliverTextRequest,
  HrcBridgeDeliverTextResponse,
  HrcBridgeTargetSelector,
  HrcBridgeTargetRequest,
  HrcBridgeTargetResponse,
  InterruptAppSessionRequest,
  ListAppSessionsRequest,
  RegisterBridgeTargetRequest,
  RegisterBridgeTargetResponse,
  RemoveAppSessionRequest,
  RemoveAppSessionResponse,
  ResolveSessionRequest,
  ResolveSessionResponse,
  RestartStyle,
  SendLiteralInputRequest,
  SendLiteralInputResponse,
  SendWindowLiteralInputRequest,
  StatusResponse,
  TerminateAppSessionRequest,
  RuntimeActionResponse,
  UnbindSurfaceRequest,
  DispatchAppHarnessTurnRequest,
  DispatchAppHarnessTurnResponse,
  SendAppHarnessInFlightInputRequest,
  SendAppHarnessInFlightInputResponse,
  ClearAppSessionContextRequest,
  ClearAppSessionContextResponse,
} from './http-contracts.js'

export type {
  HrcMessageAddress,
  HrcTargetState,
  TargetCapabilityView,
  HrcTargetRuntimeView,
  HrcTargetView,
  HrcMessageKind,
  HrcMessagePhase,
  HrcMessageExecutionState,
  HrcMessageExecution,
  HrcMessageRecord,
  HrcMessageFilter,
  EnsureTargetRequest,
  EnsureTargetResponse,
  ListTargetsRequest,
  GetTargetRequest,
  DispatchTurnBySelectorRequest,
  DispatchTurnBySelectorResponse,
  DeliverLiteralBySelectorRequest,
  DeliverLiteralBySelectorResponse,
  CaptureBySelectorRequest,
  CaptureBySelectorResponse,
  CreateMessageRequest,
  CreateMessageResponse,
  ListMessagesRequest,
  ListMessagesResponse,
  WatchMessagesRequest,
  WaitMessageRequest,
  WaitMessageResponse,
  SemanticDmRequest,
  SemanticDmResponse,
} from './hrcchat-contracts.js'
